In [3]:
# câu 1 : import module numpy và in ra version 

import numpy as np

1.14.3


In [10]:
# câu 2 : Tạo mảng 1 chiều từ 0 đến 9

import numpy as np


<type 'numpy.ndarray'>
(10,)
[0 1 2 3 4 5 6 7 8 9]


In [8]:
# câu 3: Tạo một mảng boolean 3x3 với tất cả giá trị là True

import numpy as np

# Cách 1 :
a=np.ones((3,3),dtype=np.uint8)
print(a>0)
# Cách 2 : 


# Cách 3:


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
# câu 4 : Lấy những phần tử mà thoả mãn một điều kiện cho trước của mảng một chiều

import numpy as np

# tạo mảng một chiều từ 0 đến 9

a=np.arange(0,9)
print(a)
# Tìm phần tử có giá rị lẻ 
print(a[a%2==1])

[0 1 2 3 4 5 6 7 8]
[1 3 5 7]


In [13]:
# câu 5 : Thay thế phần tử thoả mãn điều kiện cho trước bằng 1 một giá khác

import numpy as np

# tạo mảng một chiều từ 0 đến 9
a=np.arange(0,9)
print(a)
# Tìm phần tử có giá rị lẻ 
a[a%2==1]=-1
print(a)

# cách 1
# Thay thế phần tử có giá trị lẻ bằng -1


[0 1 2 3 4 5 6 7 8]
[ 0 -1  2 -1  4 -1  6 -1  8]


In [15]:
# câu 6 : Thay thế phần tử thoả mãn điều kiện cho trước bằng 1 một giá khác 
# nhưng không thay đổi mảng ban đầu

# Thay thế tất cả số lẻ bằng giá trị -1 nhưng mảng ban đầu không thay đổi

import numpy as np

# tạo mảng một chiều từ 0 đến 9
a=np.arange(0,9)
print(a)
# Cách 2 :

print(np.where(a%2==1,-1,a))
print(a)

[0 1 2 3 4 5 6 7 8]
[ 0 -1  2 -1  4 -1  6 -1  8]
[0 1 2 3 4 5 6 7 8]


In [18]:
# câu 7 : Định dạng/chuyển mảng

# Chuyển mảng 1 chiều thành mảng 2 chiều có 2 hàng ( dòng )

import numpy as np

# tạo mảng 1d gồm 10 phần tử
a=np.arange(0,10)

# mảng 2 chiều có 2 hàng
a=a.reshape(2,-1)
print(a) 


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [64]:
# câu 8:  xếp chồng 2 mảng theo chiều dọc

import numpy as np

# tạo data

# Cách 1 : 


# Cách 2 : 


# Cách 3 : 


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [67]:
# câu 9 : xếp chồng 2 mảng theo chiều ngang

import numpy as np

# tạo data

# Cách 1 : 


# Cách 2 : 


# Cách 3 : 


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [82]:
# câu 10

import numpy as np

# chỉ dùng hàm numpy có sẵn với mảng a như bên dưới
a = np.array([1,2,3])
print(a)

# tạo mảng mới lặp lại mỗi phần tử lên 3 lần

# tạo mảng mới lặp lại mảng tất cả phần tử lên 3 lần


[1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [83]:
# câu 11: Lấy phần tử chung của 2 mảng a và b 

import numpy as np

a = np.array([1,2,3,2,3,4,3,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Lấy phần tử chung của 2 mảng a và b 


array([2, 4])

In [85]:
# câu 12 : Xoá phần tử từ 1 mảng mà tồn tại trong 1 mảng khác

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Từ mảng a xoá tất cả các phần tử mà đã có trong mảng b
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [86]:
# câu 13: 

import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Lấy tất cả vị trí nơi giá trị các phần tử của 2 mảng a,b giống nhau


(array([1, 3, 5, 7]),)

In [93]:
# câu 14 : Lấy tất cả các giá trị trong 1 phạm vi cho trước từ 1 mảng

import numpy as np

a = np.array([2,6,1,9,10,3,27])

# tìm tất cả vị trí của các phần tử có giá trị trong phạm vi [5,10]




(array([1, 3, 4]),)


array([ 6,  9, 10])

In [107]:
# câu 15 : Tạo hàm xử lý trên mảng numpy

import numpy as np

def maxx(x,y):
    # Lấy số lớn nhất nhất trong 2 số
    if x >= y :
        return x
    else:
        return y

a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

# numpy.vectorize lấy hàm maxx: x,y và biến nó thành maxx: a[] -> b[].


array([6., 7., 9., 8., 9., 7., 5.])

In [109]:
import numpy as np

# lấy giá trị lớn hơn giữa a và b
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])


# dùng hàm maximum để


# dùng hàm where 


array([6, 7, 9, 8, 9, 7, 5])

In [143]:
# câu 16 : Hoán các cột trong mảng 2 chiều 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)

# Hoán cột có index 0 và index 1 trong mảng arr


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [142]:
# câu 17 :  Hoán 2 hàng trong mảng 2 chiều 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)
print(arr)

# Hoán dòng có index 0 và index 1 trong mảng arr


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [147]:
# câu 18 : 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)

# Đoản ngược hàng (dòng) trong mảng 2 chiều



[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [148]:
# câu 19 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)

# Đoản ngược cột trong mảng 2 chiều


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [155]:
# Câu 20 :  Tạo mảng 2 chiều chứa số random kiểu float từ 5 đến 10

import numpy as np


# Tạo mảng 2 chiều 5x3 từ 5 đến 10
# Cách Dùng hàm random.uniform 



[[6.47685264 7.86244037 6.14808425]
 [8.21788856 8.30326847 5.69096852]
 [7.52502254 8.05263037 5.58540214]
 [5.49201034 6.64052277 8.07812157]
 [5.17193202 8.56214323 6.66659607]]


In [451]:
# câu 21 

import numpy as np

# cho mảng a chứa các số ngẫu nhiên từ [1, 50)
a = np.random.uniform(1,50,20)
print(a)

# Thay thế tất cả các giá trị lớn hơn một giá trị cho trước thành một phạm vi [10,30]
# Thay thế tất cả các giá trị lớn hơn 30 thành 30 và dưới 10 thành 10
# Cách 1 : dùng hàm np.clip  


# Cách 2 : dùng hàm np.where



[27.63 14.64 21.8  42.39  1.23  6.96 33.87 41.47  7.7  29.18 44.67 11.25
 10.08  6.31 11.77 48.95 40.77  9.43 41.   14.43]
[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


In [128]:
# câu 22: Lấy vị trí của n giá trị đứng đầu từ một mảng numpy

import numpy as np

# cho mảng a chứa các số ngẫu nhiên từ [1, 50)
a = np.random.uniform(1,50, 20)
print(a)

Lấy vị trí của 5 giá trị lớn nhấttrong một mảng a

# Cách 1 : dùng hàm np.argsort() 


# Cách 2 : dùng hàm sort() 



[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
Vị trí :  [18  7  3 10 15]
Giá trị :  [40.99501269 41.466785   42.39403048 44.67477576 48.95256545]
Vị trí :  [18  7  3 10 15]
Giá trị :  [40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


In [237]:
# câu 23: Chuyển đổi một mảng chứa nhiều mảng thành một mảng 1d phẳng

import numpy as np


# cho array_of_arrays như sau
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)

# Chuyển đổi array_of_arrays thành mảng 1d tuyến tính phẳng 



array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


In [27]:
# câu 24: Tìm giá trị lớn nhất trong mỗi hàng của mảng 2d 

import numpy as np

# cho mảng a
a = np.random.randint(1, 10, [5,3])
print(a)


# Cách 1 : dùng np.amax


#Cách 2 : dung np.apply_along_axis và np.max



[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

In [36]:
# câu 25

import numpy as np

# cho mảng a
a = np.random.randint(1, 10, [5,3])
print(a)

# tính tỉ số min/max cho mỗi hàng trong mảng a



[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
min-by-max : [0.44444444 0.125      0.5        1.         0.11111111]
min hang :  [4 1 3 3 1]
max hang :  [9 8 6 3 9]


In [50]:
# câu 26: Tìm các vị trí có giá trị trùng lặp trong một mảng numpy

import numpy as np

# cho mảng a
a = np.random.randint(0, 5, 10)
print(a)

# Tìm các phần tử trùng lặp (lần xuất hiện thứ 2 trở đi) trong mảng đã cho
# và đánh dấu chúng là True. Lần đầu tiên xuất hiện là False.

# hint: dùng np.full và np.unique



[0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]


In [76]:
# câu 27: loại bỏ tất cả các giá trị còn thiếu (np.nan) trong một mảng

import numpy as np

# cho mảng a
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

# bỏ tất cả các giá trị nan từ một mảng numpy 1D



array([1., 2., 3., 5., 6., 7.])

In [79]:
# câu 28: 

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

# tính khoảng cách giữa hai mảng a và b, dùng np.linalg.norm


6.708203932499369

In [93]:
# câu 29: Tìm tất cả các cực đại cục bộ (hay còn gọi các đỉnh) trong một mảng 1d

import numpy as np



# cho mảng a như sau
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# Tìm tất cả các đỉnh trong một mảng numpy 1D. 
# Đỉnh là các điểm được bao quanh bởi các giá trị nhỏ hơn ở cả hai phía.

# hint: dùng np.diff và np.sign


array([2, 5])